// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag"`
	ContainerName   string `form:"containerName"`
}

type CreateContainerReq struct {
	OldName         string `json:"old_name"`
	NewName         string `json:"new_name"`
	ImageNameAndTag string `json:"image_name_and_tag"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename"`
}

type DoLoginReq struct {
	SecretKey string `form:"secret_key,optional"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid"`
}

type IdReq struct {
	Id string `path:"id"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey,optional"`
}

type MsgResp struct {
	Status string `json:"status"`
	Msg    string `json:"msg"`
}

type RemoveContainerReq struct {
	Name string `json:"name"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

type RenameContainerReq struct {
	OldName string `json:"oldName"`
	NewName string `json:"newName"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type StartContainerReq struct {
	Name string `json:"name"`
}

type StopContainerReq struct {
	Name string `json:"name"`
}

type VerifyJwtReq struct {
	Jwt string `form:"jwt,optional"`
}

type VersionMsgResp struct {
	Version   string `json:"version"`
	BuildDate string `json:"build_date"`
}

type VersionReq struct {
	Type string `form:"type"`
}

type GetNewImageReq struct {
	ImageNameAndTag string `json:"image_name_and_tag"`
}

// ======== 群组管理类型 ========

type GroupCreateReq struct {
	Name        string `json:"name"`
	CronExpr    string `json:"cronExpr,optional"`
	AutoUpdate  bool   `json:"autoUpdate,optional"`
	CheckUpdate bool   `json:"checkUpdate,default=true"`
	Priority    int    `json:"priority,default=100"`
	Enabled     bool   `json:"enabled,default=true"`
}

type GroupUpdateReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	CronExpr    string `json:"cronExpr,optional"`
	AutoUpdate  bool   `json:"autoUpdate,optional"`
	CheckUpdate bool   `json:"checkUpdate,optional"`
	Priority    int    `json:"priority,optional"`
	Enabled     bool   `json:"enabled,optional"`
}

type GroupIdReq struct {
	Id int64 `path:"id"`
}

type RuleCreateReq struct {
	GroupId  int64  `json:"groupId"`
	RuleType string `json:"ruleType"`
	Pattern  string `json:"pattern"`
}

type RuleIdReq struct {
	Id int64 `path:"id"`
}

type ContainerAssignReq struct {
	GroupId       int64  `json:"groupId"`
	ContainerId   string `json:"containerId"`
	ContainerName string `json:"containerName"`
}

type ContainerAssignIdReq struct {
	Id int64 `path:"id"`
}

type RulePreviewReq struct {
	RuleType string `form:"ruleType"`
	Pattern  string `form:"pattern"`
}

type HistoryListReq struct {
	Page    int   `form:"page,default=1"`
	Size    int   `form:"size,default=20"`
	GroupId int64 `form:"groupId,optional"`
}

// ======== 设置管理类型 ========

type BarkConfigReq struct {
	Enabled bool   `json:"enabled"`
	Server  string `json:"server"`
	Key     string `json:"key"`
}

type BarkTestReq struct {
	Server string `json:"server"`
	Key    string `json:"key"`
}
