// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag"`
	ContainerName   string `form:"containerName"`
}

type CreateContainerReq struct {
	OldName         string `json:"old_name"`
	NewName         string `json:"new_name"`
	ImageNameAndTag string `json:"image_name_and_tag"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename"`
}

type DoLoginReq struct {
	SecretKey string `form:"secret_key,optional"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid"`
}

type ContainerLogsReq struct {
	Id    string `path:"id"`
	Token string `form:"token,optional"`
	Tail  string `form:"tail,default=100"`
}

type IdReq struct {
	Id string `path:"id"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey,optional"`
}

type MsgResp struct {
	Status string `json:"status"`
	Msg    string `json:"msg"`
}

type RemoveContainerReq struct {
	IdReq
	Force                   bool `form:"force,default=false"`
	DeleteImage             bool `form:"deleteImage,default=false"`
	DeleteRelatedContainers bool `form:"deleteRelatedContainers,default=false"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

type UpdateImageSourceReq struct {
	IdReq
	SourceType   string `json:"sourceType"`            // remote, local, private
	RegistryHost string `json:"registryHost,optional"` // 私有 Registry 主机（当 sourceType=private 时使用）
}

type UpdateImageTagReq struct {
	IdReq
	NewTag string `json:"newTag"` // 新的镜像标签
}

type RenameContainerReq struct {
	OldName string `json:"oldName"`
	NewName string `json:"newName"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type StartContainerReq struct {
	Name string `json:"name"`
}

type StopContainerReq struct {
	Name string `json:"name"`
}

type VerifyJwtReq struct {
	Jwt string `form:"jwt,optional"`
}

type VersionMsgResp struct {
	Version   string `json:"version"`
	BuildDate string `json:"build_date"`
}

type VersionReq struct {
	Type string `form:"type"`
}

type GetNewImageReq struct {
	ImageNameAndTag string `json:"image_name_and_tag"`
}

// ======== 群组管理类型 ========

type GroupCreateReq struct {
	Name               string `json:"name"`
	GroupType          string `json:"groupType,optional,default=container"`
	CronExpr           string `json:"cronExpr,optional"`
	AutoUpdate         bool   `json:"autoUpdate,optional"`
	CheckUpdate        bool   `json:"checkUpdate,default=true"`
	Priority           int    `json:"priority,default=100"`
	Enabled            bool   `json:"enabled,default=true"`
	RestartAfterUpdate bool   `json:"restartAfterUpdate,optional"` // 重启容器
	StartContainers    bool   `json:"startContainers,optional"`    // 启动容器
	StopContainers     bool   `json:"stopContainers,optional"`     // 停止容器
}

type GroupUpdateReq struct {
	Id                 int64  `path:"id"`
	Name               string `json:"name,optional"`
	GroupType          string `json:"groupType,optional"`
	CronExpr           string `json:"cronExpr,optional"`
	AutoUpdate         bool   `json:"autoUpdate,optional"`
	CheckUpdate        bool   `json:"checkUpdate,optional"`
	Priority           int    `json:"priority,optional"`
	Enabled            bool   `json:"enabled,optional"`
	RestartAfterUpdate bool   `json:"restartAfterUpdate,optional"` // 重启容器
	StartContainers    bool   `json:"startContainers,optional"`    // 启动容器
	StopContainers     bool   `json:"stopContainers,optional"`     // 停止容器
}

type GroupIdReq struct {
	Id int64 `path:"id"`
}

type RuleCreateReq struct {
	GroupId  int64  `json:"groupId"`
	RuleType string `json:"ruleType"`
	Pattern  string `json:"pattern"`
}

type RuleIdReq struct {
	Id int64 `path:"id"`
}

type ContainerAssignReq struct {
	GroupId       int64  `json:"groupId"`
	ContainerId   string `json:"containerId"`
	ContainerName string `json:"containerName"`
}

type ContainerAssignIdReq struct {
	Id int64 `path:"id"`
}

type RulePreviewReq struct {
	RuleType string `form:"ruleType"`
	Pattern  string `form:"pattern"`
}

type HistoryListReq struct {
	Page    int   `form:"page,default=1"`
	Size    int   `form:"size,default=20"`
	GroupId int64 `form:"groupId,optional"`
}

// ======== 设置管理类型 ========

type BarkConfigReq struct {
	Enabled    bool   `json:"enabled"`
	Server     string `json:"server"`
	Key        string `json:"key"`
	NotifyMode string `json:"notifyMode"` // always, failure_only, success_only
	ShowDetail bool   `json:"showDetail"` // 是否显示具体明细
}

type BarkTestReq struct {
	Server string `json:"server"`
	Key    string `json:"key"`
}

// ======== 容器事件通知配置 ========

type ContainerEventConfigReq struct {
	Enabled           bool `json:"enabled"`           // 是否启用容器事件通知
	NotifyOnStart     bool `json:"notifyOnStart"`     // 容器启动时通知
	NotifyOnStop      bool `json:"notifyOnStop"`      // 容器停止时通知
	NotifyOnDie       bool `json:"notifyOnDie"`       // 容器异常退出时通知
	NotifyOnRestart   bool `json:"notifyOnRestart"`   // 容器重启时通知
	NotifyOnCreate    bool `json:"notifyOnCreate"`    // 容器创建时通知
	NotifyOnDestroy   bool `json:"notifyOnDestroy"`   // 容器删除时通知
	NotifyOnHealthy   bool `json:"notifyOnHealthy"`   // 容器健康检查通过时通知
	NotifyOnUnhealthy bool `json:"notifyOnUnhealthy"` // 容器健康检查失败时通知
}

// ======== Registry 镜像配置类型 ========

type RegistryMirrorsConfigReq struct {
	Enabled bool     `json:"enabled"` // 是否启用自定义镜像
	Mirrors []string `json:"mirrors"` // 镜像地址列表
}

type RegistryTestReq struct {
	Address string `json:"address"` // 要测试的 Registry 地址
}

// ======== 代理配置类型 ========

type ProxyConfigReq struct {
	Enabled  bool   `json:"enabled"`            // 是否启用代理
	Type     string `json:"type"`               // http, https, socks5
	Host     string `json:"host"`               // 代理服务器地址
	Port     int    `json:"port"`               // 代理端口
	Username string `json:"username,optional"`  // 代理用户名（可选）
	Password string `json:"password,optional"`  // 代理密码（可选）
}

type ProxyTestReq struct {
	Type     string `json:"type"`               // http, https, socks5
	Host     string `json:"host"`               // 代理服务器地址
	Port     int    `json:"port"`               // 代理端口
	Username string `json:"username,optional"`  // 代理用户名（可选）
	Password string `json:"password,optional"`  // 代理密码（可选）
}

// ======== 性能配置类型 ========

type PerformanceConfigReq struct {
	LowPowerMode         bool `json:"lowPowerMode"`         // 低性能模式
	MaxConcurrentChecks  int  `json:"maxConcurrentChecks"`  // 镜像检查最大并发数
	CheckIntervalMinutes int  `json:"checkIntervalMinutes"` // 镜像自动检查间隔（分钟）
	DisableAutoCheck     bool `json:"disableAutoCheck"`     // 禁用启动时自动检查
}

// ======== 私有 Registry 配置类型 ========

type PrivateRegistryItem struct {
	Name     string `json:"name"`              // 名称
	Host     string `json:"host"`              // 主机地址
	Username string `json:"username,optional"` // 用户名
	Password string `json:"password,optional"` // 密码
	Insecure bool   `json:"insecure,optional"` // 是否允许不安全连接
}

type PrivateRegistriesConfigReq struct {
	Enabled    bool                  `json:"enabled"`    // 是否启用
	Registries []PrivateRegistryItem `json:"registries"` // 私有 Registry 列表
}

type PrivateRegistryTestReq struct {
	Host     string `json:"host"`              // 主机地址
	Username string `json:"username,optional"` // 用户名
	Password string `json:"password,optional"` // 密码
	Insecure bool   `json:"insecure,optional"` // 是否允许不安全连接
}

// ======== 环境管理类型 ========

type EnvironmentCreateReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	EnvType     string `json:"envType,default=remote"`
	URL         string `json:"url,optional"`
	SecretKey   string `json:"secretKey,optional"`
	Icon        string `json:"icon,optional"`
}

type EnvironmentUpdateReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	URL         string `json:"url,optional"`
	SecretKey   string `json:"secretKey,optional"`
	Icon        string `json:"icon,optional"`
}

type EnvironmentIdReq struct {
	Id int64 `path:"id"`
}

type EnvironmentTestReq struct {
	URL       string `json:"url"`
	SecretKey string `json:"secretKey"`
}

// ======== 容器删除相关类型 ========

type DependentContainer struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type ImageDependencyInfo struct {
	ImageID             string               `json:"imageId"`
	ImageName           string               `json:"imageName"`
	DependentContainers []DependentContainer `json:"dependentContainers"`
}
