// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	auth "github.com/xcz1997/dockerCopilot/internal/handler/auth"
	container "github.com/xcz1997/dockerCopilot/internal/handler/container"
	"github.com/xcz1997/dockerCopilot/internal/handler/group"
	image "github.com/xcz1997/dockerCopilot/internal/handler/image"
	progress "github.com/xcz1997/dockerCopilot/internal/handler/progress"
	"github.com/xcz1997/dockerCopilot/internal/handler/settings"
	version "github.com/xcz1997/dockerCopilot/internal/handler/version"
	"github.com/xcz1997/dockerCopilot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects",
				Handler: container.ProjectsListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/image/pull",
				Handler: image.PullHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks",
				Handler: progress.ListTasksHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/scheduler/status",
				Handler: progress.SchedulerStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 群组管理路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/groups",
				Handler: group.GroupListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group/:id",
				Handler: group.GroupGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group",
				Handler: group.GroupCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/group/:id",
				Handler: group.GroupUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/group/:id",
				Handler: group.GroupDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/rule",
				Handler: group.RuleCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/group/rule/:id",
				Handler: group.RuleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group/rule/preview",
				Handler: group.RulePreviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/container",
				Handler: group.ContainerAssignHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/group/container/:id",
				Handler: group.ContainerUnassignHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers/assignments",
				Handler: group.ContainerAssignmentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/:id/check",
				Handler: group.GroupCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/:id/update",
				Handler: group.GroupUpdateActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group/history",
				Handler: group.HistoryListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 设置管理路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/settings/bark",
				Handler: settings.BarkGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/settings/bark",
				Handler: settings.BarkSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/settings/bark/test",
				Handler: settings.BarkTestHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
